package com.example.android.sunshine.app;

import android.support.v7.app.ActionBarActivity;
import android.support.v4.app.Fragment;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ArrayAdapter;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


public class MainActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        if (savedInstanceState == null) {
            getSupportFragmentManager().beginTransaction()
                    .add(R.id.container, new PlaceholderFragment())
                    .commit();
        }
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    /**
     * A placeholder fragment containing a simple view.
     */
    public static class PlaceholderFragment extends Fragment {

        public PlaceholderFragment() {
        }

        @Override
        public View onCreateView(LayoutInflater inflater, ViewGroup container,
                                 Bundle savedInstanceState) {
            View rootView = inflater.inflate(R.layout.fragment_main, container, false);

            String[] forecastArray = {
                    "Today - Sunny - 88/63",
                    "Tomorrow - Foggy - 70/40",
                    "Wed - Cloudy - 72/63",
                    "Thu - Rainy - 70/60",
                    "Fri - Thundery - 50/40",
                    "Sat - Apocalpytic 1000/1000",
                    "Sun - Barren - 0/0"
            };

            //Create an Array List with all our raw data
            List<String> weekForecast = new ArrayList<String>(Arrays.asList(forecastArray));

            /*
            * Create an array adapter, to pass our raw data to our listview
            * The adapter can be initialised using 4 parameters,
            *  R is a java class that creates human readable identifiers for our resources
            *  it is an autogenerated file
            *  R.layout is a file, R.id is a xml element with a matching id
            */
           ArrayAdapter<String> mForecastAdapter = new ArrayAdapter<String>(
                   //context
                   getActivity(),
                   //id of list item layout => name of the xml file
                   R.layout.list_item_forecast,
                   //id of textview => id of textview that was defined inside the xml file
                   R.id.list_item_forecast_textview,
                   //list of data
                   weekForecast
           );

            return rootView;
        }
    }
}
